### ISSUE TITLE
EEEOR!!!Recon process aborted. To RESHAPE the number of elements must not change

### ISSUE THREAD

**Issue by duancaohui** [leoliuf/MRiLab#19]
My systerm is Windows10, Matlab 2017a, MRilab 1.3
When I do a simulation, all seems successful, and the  scan progress bar increase 0% to 100%
![qq 20180515214808](https://user-images.githubusercontent.com/11900034/40060694-c95e4120-5889-11e8-907d-8de1cd6fb9cd.png)
however at the end of simulation, two  Out of error
![1](https://user-images.githubusercontent.com/11900034/40060852-1af2dbe0-588a-11e8-8b80-8e9bf7071641.png)
![2](https://user-images.githubusercontent.com/11900034/40060859-1f47f356-588a-11e8-9cff-ef9cc021a6a5.png)
I don't what the error mean, can you help me

**there are some information about my simulation**
1. Vobj
size:512,512,35
XDimRes:1.5mm
ZDimRes:5mm
Gyro:73997000
2.Sequence
PSD_FIESTA3D
3.Imaging
![3](https://user-images.githubusercontent.com/11900034/40061091-b6a9e088-588a-11e8-9d9d-a5766665f682.png)

**Comment by leoliuf** [comment]
This usually occurs when the simulator accumulates unequal data to the prescribed size. See the pulse waveform from your prescription. I duplicated the experiment using the provided info and found the pulse waveform overlapping. 
![image](https://user-images.githubusercontent.com/6468385/40071041-5cdcce62-5835-11e8-8d6a-7f90aea5aaed.png)
You might want to redesign your experiment (i.e. increase BandWidth) to avoid this error.

**Comment by duancaohui** [comment]
Hi, Dr. Liu, Thanks for your kindly answers!
I resesign my experiment, increase BandWidth from 19.2 to 51.2 KHZ，no errors anymore.
**However the simulation images are so strange, just a white line shown below:**
![4](https://user-images.githubusercontent.com/11900034/40101749-f604e77e-591a-11e8-85ad-0dee2da72c46.png)
**Simulation Settings:**
![5](https://user-images.githubusercontent.com/11900034/40103221-4b2cc3a8-591f-11e8-8bb3-810915afd9f7.png)
![6](https://user-images.githubusercontent.com/11900034/40103265-74ad017a-591f-11e8-991f-d4587f8db05f.png)

By the way, I want to simulate hyperpolarized 129 Xenon-MRI, The longitudinal magnetization of hyperpolarized media, such as hyperpolarized129Xe, 3He, etc., is nonrenewable,how to add this to   Bloch-equation Solving Kernels

**Comment by leoliuf** [comment]
FIESTA (a.k.a bSSFP) typically has a sequence waveform like this
![image](https://user-images.githubusercontent.com/6468385/40148624-94fec106-5934-11e8-9a67-d23f496b872b.png)
Your prescription loses rewinder gradient due to small TE and TR. Notice the rewinder is apart from the main gradient by CV1 and CV2 which need to be modified to appropriate value.
![image](https://user-images.githubusercontent.com/6468385/40148663-cac0a5b6-5934-11e8-9bad-52339e1e54c1.png)
For the Xenon contrast question, you need to create multi-component phantom and give a ChemShift value to your Xenon parts.
