### ISSUE TITLE
Converting BrainWeb models and simulating intensity non-uniformity

### ISSUE THREAD

**Issue by kovimesterr** [leoliuf/MRiLab#27]
Dear Fang Liu,

Thank you very much for answering my former questions. I have tried the [20 new anatomical McGill BrainWeb models](https://brainweb.bic.mni.mcgill.ca/anatomic_normal_20.html).  Comparing to the normal model, the new models' file format is a bit different, thus I made a function in MatLab that converts the new models to VObj structures. I have attached the code, maybe it can be useful in the future. I have already tried the new models, they work perfectly in MRiLab.

Regarding the simulations I have some questions:
1) In addition to the noiselevel, is it possible to simulate other distortions like the [intensity non-uniformity](https://brainweb.bic.mni.mcgill.ca/cgi/bw/submit_request)? 
2) In the 20 new anatomical models there are additional tissues like Dura and Marrow. Is there any convention to set these values like you did in the "Phantom Parameter Table.xls"? Currently, I dont consider these tissue types, i.e. I just set their tissue parameters to zero.

Thank you in advance for your help.

Best regards,
Peter

[convert_BrainWeb_to_MRiLab.zip](https://github.com/leoliuf/MRiLab/files/3503057/convert_BrainWeb_to_MRiLab.zip)

**Comment by leoliuf** [comment]
Thank Peter,

Thank you for providing the code for converting the new phantom to VObj. I am glad it works for you. To answer your remaining questions,

1. It's possible to add non-uniform noise based on the field. You need to provide the field map and then modify DoAddNoise.m script to add customized noise in k-space.
2. You might want to find some works of literature for estimating MR tissue properties for Dura and Marrow, then substitute the default values in my table. 

Hope my answer helps. 

P.S. would you mind also adding the original questions in your first email to me in this thread. Thx

**Comment by kovimesterr** [comment]
My former questions:

Dear Fang Liu,

I am working on a machine learning project in which we would like to test our AI algorithms on the problem of brain MRI image segmentation. In order to build up a dataset for training and testing, we are currently looking for synthtic data generators that simulate measurements and provide the groundtruth as well. This is how I found your paper on MRiLab. The work is impressive and the way you published it is professional. I very much appreciate that you shared the code, the documentation, and even youtube videos for demonstrations. This really supports the community and speeds up the experimenting process. I also want to try MRiLab in our project, and so I have some technical questions: 

1) We need multi-echo brain mri measurements for which I got an error message. According to the documentation, the number of echos in ME_TEs must match TEPerTR. 
Following this instruction, I set TEPerTR=2, and ME_TEs=[500e-3 1000e-3], however I still got an error. Enclosed you can find the screenshots that I made about the settings and the errors. 

2) In the project, we want to develop machine learning algorithms to segment the tissues in brain mri images. Therefore, we need the groundtruth image masks for each tissue. 
I guess the groundtruth brain model with class labels is provided in "BrainModel.mat" in the Resources folder. Is my assumption correct? So for any brain mri measurement simulation, the groundtruth is contained in this file?  

3) I have seen you are using the [McGill BrainWeb brain model](https://brainweb.bic.mni.mcgill.ca/brainweb/anatomic_normal.html). Are there other publicly available brain models that we could use for test data? I mean training the algorithms on one model and then test it on independent data coming from another model. Are there any conventions which models to use for training and testing?  

Thank you in advance for your help.

Best regards,
Peter 


![error](https://user-images.githubusercontent.com/4989639/63054376-022f8380-bee4-11e9-821a-109906523e03.png)
![seqlist_settings](https://user-images.githubusercontent.com/4989639/63054378-022f8380-bee4-11e9-9922-95723f9ebaa5.png)

**Comment by leoliuf** [comment]
Thx, here is my answer to Peter's previous email. I put here just in case some other people have similar questions and are trying to find a similar solution.

--------------
Dear Peter,

Thank you for your email. To answer your questions.

1) You are halfway through the problem. The ME_TEs provides TE value for each echo you want to image. However, you need to create an imaging acquisition gradient into the sequence to actually use the TE value to acquire MRI data. You need to modify the PSD_GRE3D sequence to incorporate the new echo information. Check PSD_AFI to see an example about multi-echo.

2) Yes, BrainModel.mat is the brain anatomy phantom I used to create those default MR models. You can assign MR properties (e.g. T1, T2, Rho, etc.) to different tissues based on the anatomy phantom to create your own.

3) There should be plenty of anatomy phantom from McGill Brainweb, I heard they recently released 20 individual brain anatomy which might be helpful for ML training and testing and you might want to check at https://brainweb.bic.mni.mcgill.ca/brainweb/anatomic_normal_20.html

Thanks. I would prefer if you want to ask questions on GitHub (https://github.com/leoliuf/MRiLab/issues) so that more people might gain help from our conversation.

Fang
